[workspace]
resolver = "2"

members = [
    "crates/evernight_core",
    "crates/evernight_math",
    "crates/evernight_runtime",
    "crates/evernight_script",
    "crates/evernight_lua",
    "crates/evernight_godot",

    "tools/benchmark",
]

[profile.release]
debug = 1          # 保留行号信息，不影响优化级别
