[package]
name = "evernight_script"
version = "0.1.0"
edition = "2024"

[features]
benchmark = ["dep:evernight_benchmark", "evernight_runtime/benchmark"]

[dependencies]
evernight_core      = { path = "../evernight_core" }
evernight_math      = { path = "../evernight_math" }
evernight_input     = { path = "../evernight_input" }
evernight_runtime   = { path = "../evernight_runtime" }
evernight_benchmark = { path = "../evernight_benchmark", optional = true }
